### ISSUE TITLE
Space Travel Hub 

### ISSUE THREAD

**Issue by cvalencia1991** [cvalencia1991/SpaceTravelHub#25]
In its description, paste a link to your GitHub project.

- Link of the project https://github.com/users/cvalencia1991/projects/6/views/1
- This project is for Two People 
@jfoyarzo and @cvalencia1991

**Comment by cynthiainga** [comment]
Hi @cvalencia1991 & @jfoyarzo, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] Descriptive issue ✔️ 
- [ ] Good setup of a kanban board

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by cvalencia1991** [comment]
Thanlk you very much :smile:
